onlyBuiltDependencies:
  - esbuild
# https://pnpm.io/supply-chain-security#prevent-exotic-transitive-dependencies
blockExoticSubdeps: true
# https://pnpm.io/supply-chain-security#delay-dependency-updates
minimumReleaseAge: 1440
# https://pnpm.io/supply-chain-security#enforce-trust-with-trustpolicy
trustPolicy: no-downgrade
